### ISSUE TITLE
Add additional maintainer(s)

### ISSUE THREAD

**Issue by Yepoleb** [serverstf/python-valve#47]
There are still a lot of unmerged forks and it would be nice to have a complete upstream branch again. As you apparently don't have the time to maintain this properly, I suggest you add other people who are willing to take care of the project.

**Comment by Holiverh** [comment]
Hi, yes, what you say is reasonable. I alluded to the fact I should have more time for Python-valve "freed up" soon on a [separate issue a while ago](https://github.com/Holiverh/python-valve/issues/42#issuecomment-312966226). Turns out my idea of *soon* wasn't quite accurate. That is indeed changing now; I've been working on dependent project recently so you might start seeing some changes coming through from that.

As for additional maintainers. I'm mostly certainly not going to be hostile to anyone putting their name forward as a volunteer. So I'll leave this open as a place for anyone to do that if they so wish.

**Comment by Yepoleb** [comment]
I'd be up for it. @thel3l how about you?

**Comment by thel3l** [comment]
I'd love to @Yepoleb!

**Comment by Holiverh** [comment]
Don't worry I haven't forgotten this! Just thought I'd leave it open for a bit to see if there was anyone else out there who was interested.

I'm also toying with the idea of moving this repository to a new GitHub organisation. Once I work out the who/how/what/where of that I'll get around to the whole, *adding new maintainers* thing. I've got a potentially busy three or so days coming up -- and what time I do have will go into finalising the next Python-valve release. So sometime after then.

✌️
